{% set version = "1.36.0" %}
{% set sha256 = "b593b2fd382489909c96c62c6e180054c3332b950be3d73e0cb0d21ea8afb3c5" %}

package:
  name: aria2
  version: {{ version }}

source:
  url: https://github.com/aria2/aria2/releases/download/release-{{ version }}/aria2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - pkg-config  # [osx]

  host:
    - zlib
    - openssl  # [linux]
    - sqlite
    - libssh2
    - c-ares
    - libxml2
    - gmp  # [osx]

  run:
    - zlib
    - openssl  # [linux]
    - sqlite
    - libssh2
    - c-ares
    - libxml2
    - gmp  # [osx]

test:
  commands:
    - aria2c -v

about:
  home: https://aria2.github.io/
  summary: aria2 is a lightweight multi-protocol & multi-source, cross platform download utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  dev_url: https://github.com/aria2/aria2/

extra:
  recipe-maintainers:
    - acaprez
